apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: primary-observer
  namespace: fleet-local
spec:
  branch: main
  clientSecretName: null
  paths:
  - /primary_observer/prerequisites
  - /primary_observer/istio
  repo: https://github.com/shpwrck/KMC-SPOG
  targets:
  - clusterSelector:
      matchLabels:
        role: primary
