apiVersion: v1
data:
  overlay-config.yaml: |2
           apiVersion: install.istio.io/v1alpha1
           kind: IstioOperator
           spec:
             values:
               global:
                 multiCluster:
                   clusterName: primary
                 network: primary
                 meshNetworks:
                   primary:
                     endpoints:
                     - fromRegistry: primary
                     gateways:
                     - registry_service_name: istio-ingressgateway.istio-system.svc.cluster.local
                       port: 443
                   remote:
                     endpoints:
                     - fromRegistry: remote
                     gateways:
                     - registry_service_name: istio-ingressgateway.istio-system.svc.cluster.local
                       port: 443
                 meshExpansion:
                   enabled: true
kind: ConfigMap
metadata:
  name: istio-installer-overlay
  namespace: istio-system
