apiVersion: v1
kind: Service
metadata:
  name: thanos
  namespace: cattle-monitoring-system
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: nginx-http
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: grpc
    port: 10901
    protocol: TCP
    targetPort: 10901
  - name: http
    port: 10902
    protocol: TCP
    targetPort: 10902
  selector:
    app: prometheus
  sessionAffinity: None
  type: NodePort
