apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: thanos-sample-query
  namespace: cattle-monitoring-system
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: thanos-sample-query
          servicePort: 10902
        pathType: ImplementationSpecific
