apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: primary
  namespace: fleet-default
spec:
  branch: main
  clientSecretName: null
  paths:
  - /primary/prerequisites
  - /primary/istio
  repo: https://github.com/shpwrck/KMC-SPOG
  targets:
  - clusterSelector:
      matchLabels:
        role: primary
