apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: primary
  namespace: fleet-default
spec:
  branch: main
  clientSecretName: null
  paths:
  - /primary/prerequisites/monitoring-crd
  - /primary/prerequisites/monitoring
  - /primary/istio/istio
  - /primary/istio/istio-resources
  - /primary/istio/kiali
  - /primary/istio/thanos  
  repo: https://github.com/shpwrck/KMC-SPOG
  targets:
  - clusterSelector:
      matchLabels:
        role: primary
