apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: remote
  namespace: fleet-default
spec:
  branch: main
  clientSecretName: null
  paths:  
  - /remote/prerequisites/monitoring-crd
  - /remote/prerequisites/monitoring
  - /remote/istio/istio-resources
  - /remote/istio/istio
  - /remote/istio/kiali
  repo: https://github.com/shpwrck/KMC-SPOG
  targets:
  - clusterSelector:
      matchLabels:
        role: remote
