apiVersion: v1
kind: Service
metadata:
  name: thanos-sidecar-nodeport
  namespace: cattle-prometheus
spec:
  externalTrafficPolicy: Local
  ports:
  - name: grpc
    port: 10901
    protocol: TCP
    targetPort: 10901
  - name: http
    port: 10902
    protocol: TCP
    targetPort: 10902
  publishNotReadyAddresses: true
  selector:
    app: prometheus
  sessionAffinity: None
  type: NodePort

